# Generated by Django 4.2 on 2023-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playground", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish"),
        )
    ]
